baseURL = "https://cdp.yt/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
title = "Cômputos de Porão"
theme = "minos"
enableEmoji = true
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  customCss = ["css/custom.css"]
  smartToc = true
  noPostNavigation = true
